#' @importFrom blockr.core register_blocks
register_lm_blocks <- function() {
  blockr.core::register_blocks(
    c(
      "new_model_block",
      "new_lm_block",
      "new_coef_block",
      "new_anova_block",
      "new_model_summary_block",
      "new_coefplot_block",
      "new_diagnostic_plot_block",
      "new_residual_explorer_block",
      "new_check_model_block",
      "new_regression_3d_block",
      "new_parameters_block",
      "new_performance_block",
      "new_effectsize_block",
      "new_standardize_block",
      "new_report_block",
      "new_descriptives_block",
      "new_correlation_block",
      "new_frequencies_block",
      "new_ttest_block",
      "new_cohens_d_block",
      "new_normality_check_block",
      "new_homogeneity_check_block",
      "new_nonparametric_block"
    ),
    name = c(
      "Model",
      "Linear Model",
      "Coefficients Table",
      "ANOVA Table",
      "Model Summary",
      "Coefficient Plot",
      "Diagnostic Plots",
      "Residual Explorer",
      "Check Model",
      "3D Regression Plot",
      "Parameters",
      "Performance",
      "Effect Size",
      "Standardized Parameters",
      "Auto-Narrative",
      "Descriptives",
      "Correlation Matrix",
      "Frequencies",
      "T-Test",
      "Cohen's d",
      "Normality Check",
      "Homogeneity of Variance",
      "Nonparametric Test"
    ),
    description = c(
      "Fit statistical models (lm, logistic, multinomial, ordinal, mixed-effects). Select model type and variables.",
      "Fit a linear model using lm(). Select response and predictor variables.",
      "Extract model coefficients with standard errors, t-statistics, and p-values using broom::tidy().",
      "ANOVA table showing the decomposition of variance for model terms.",
      "HTML summary with coefficients, statistics, and diagnostic tests. Works with any broom-compatible model.",
      "Dot-and-whisker plot of coefficients with confidence intervals.",
      "Standard diagnostic plots: Residuals vs Fitted, Q-Q, Scale-Location, and Leverage.",
      "Interactive residual exploration with plotly. Click to identify observations.",
      "Comprehensive model diagnostics using performance package: VIF, normality, homoscedasticity, outliers.",
      "Interactive 3D scatter plot with regression plane for models with 2 predictors.",
      "Publication-style coefficient table via parameters::model_parameters(). Better-formatted than broom::tidy.",
      "Compact one-row model fit headline (R^2, AIC, BIC, RMSE) via performance::model_performance().",
      "Eta-squared / omega-squared / epsilon-squared effect sizes for ANOVA terms via effectsize.",
      "Standardized regression coefficients (beta) with CIs via effectsize::standardize_parameters().",
      "Auto-generated APA-style narrative paragraph describing the model or test via report::report().",
      "Per-variable summary statistics (mean, SD, IQR, range, skewness, kurtosis) via parameters::describe_distribution().",
      "Pairwise correlation matrix (Pearson / Spearman / Kendall) via correlation::correlation().",
      "Frequency counts and proportions for categorical columns.",
      "Adaptive t-test block: one-sample, paired, or independent (Welch / Student) via stats::t.test().",
      "Cohen's d effect size from a t-test result via effectsize::effectsize().",
      "Shapiro-Wilk normality check, optionally split by group. Emits per-group decisions (OK / Concern / Reject).",
      "Bartlett's test for homogeneity of variance across groups. Emits a decision flag.",
      "Adaptive Wilcoxon / Mann-Whitney U block, mirroring the t-test block's type picker."
    ),
    category = c(
      "transform",
      "transform",
      "transform",
      "transform",
      "transform",
      "plot",
      "plot",
      "plot",
      "plot",
      "plot",
      "transform",
      "transform",
      "transform",
      "transform",
      "transform",
      "transform",
      "transform",
      "transform",
      "transform",
      "transform",
      "transform",
      "transform",
      "transform"
    ),
    icon = c(
      "calculator",
      "graph-up",
      "table",
      "bar-chart",
      "clipboard-data",
      "bullseye",
      "grid-3x3",
      "search",
      "check2-square",
      "box",
      "list-columns",
      "speedometer2",
      "rulers",
      "arrow-bar-up",
      "chat-quote",
      "clipboard2-data",
      "grid-3x3-gap",
      "bar-chart-line",
      "arrow-left-right",
      "rulers",
      "shield-check",
      "shield-shaded",
      "alphabet"
    ),
    package = utils::packageName(),
    overwrite = TRUE
  )
}
